language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - xutils-dev
            - libxcb-util0-dev
script:
    - git submodule update --init
    - ./autogen.sh
    - make && make check
